import pytest

def test_quote_grounding(mock_themes_output, raw_reviews_sample):
    """
    Ensures every 'high_signal_quote' generated by the LLM 
    actually exists in the source review text.
    """
    # Flatten source reviews into a single list of strings
    source_texts = [r["review_text"] for r in raw_reviews_sample]
    
    for theme in mock_themes_output:
        for quote in theme.get("high_signal_quotes", []):
            # Strip quotes for comparison
            clean_quote = quote.strip('"').strip("'")
            # Check if this quote exists as a substring in ANY source review
            exists = any(clean_quote in source for source in source_texts)
            assert exists, f"Hallucination Detected: Quote '{quote}' not found in source reviews."

def test_summary_grounding_placeholder():
    """
    Placeholder for future NLI (Natural Language Inference) based 
    hallucination detection.
    """
    # In a production setting, we would use another LLM to verify 
    # if the summary is 'entailed' by the source reviews.
    pass
